# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.13.0

clone:
  depth: full
  
pipelines:
  branches:
    master:
    - step:
        deployment: production  
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/gregsoares.git
